### ISSUE TITLE
pages

### ISSUE THREAD

**Issue by ChristopherTeodoro** [abielh06/codeRunners#5]
Nick and I have chosen to create a separate app that will hook into pages on react app.  We are working on rendering html & css.

**Comment by ChristopherTeodoro** [comment]
let us know if you get comments working on react by itself though.

**Comment by ChristopherTeodoro** [comment]
css for login is complete.  working on everything else for styling now.

**Comment by abielh06** [comment]
routes are working for the post and comment.  I'll try to implement the
functions into our react framework.

**Comment by ChristopherTeodoro** [comment]
great job
